export default [
  {
    id: 1,
    title: "Ноутбуки та комп'ютери",
    labelSrc: 'laptop',
    name: 'category',
    params: 'laptops-and-computers',
  },
  {
    id: 3,
    title: 'Смартфони та планшети',
    labelSrc: 'mobile-screen-button',
    name: 'category',
    params: 'smartphones-and-tablets',
  },
  {
    id: 4,
    title: 'Телевізори та мультимедіа',
    labelSrc: 'tv',
    name: 'category',
    params: 'tvs-and-multimedia',
  },
  {
    id: 5,
    title: 'Побутова техніка',
    labelSrc: 'kitchen-set',
    name: 'category',
    params: 'household-appliances',
  },
  {
    id: 6,
    title: 'Ігрові консолі та геймінг',
    labelSrc: 'gamepad',
    name: 'category',
    params: 'consoles-and-gaming',
  },
  {
    id: 7,
    title: 'Фото та відео',
    labelSrc: 'camera-retro',
    name: 'category',
    params: 'photo-and-video',
  },
  {
    id: 8,
    title: 'Аудіо',
    labelSrc: 'radio',
    name: 'category',
    params: 'audio',
  },
  {
    id: 9,
    title: 'Аксесуари',
    labelSrc: 'headset',
    name: 'category',
    params: 'accessories',
  },
  {
    title: 'Переглянути всі категорії',
    labelSrc: 'list',
    name: 'catalogue',
  },
]
